### ISSUE TITLE
add CI integration and run format checker, linter, etc

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#10]

**Comment by fabiosantoscode** [comment]
This is with CircleCI right? I think if we create a configuration folder it should automatically apply. I'll get on this.

**Comment by shcheklein** [comment]
yes! thanks, @fabiosantoscode

**Comment by shcheklein** [comment]
Reopening for now, need to fix small issues most likely after actually running it.

Need to check if it runs for forks.

**Comment by fabiosantoscode** [comment]
Looks like the checks are not running @shcheklein (see #105). Was this repository added to CircleCI?

**Comment by shcheklein** [comment]
Yes, it was. Please check this and let me know if we need to add you a collaborator or enable something else on the CircleCi - https://circleci.com/blog/managing-secrets-when-you-have-pull-requests-from-outside-contributors/

**Comment by shcheklein** [comment]
and this https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/

**Comment by fabiosantoscode** [comment]
@shcheklein there seems to be a setting to enable building on forked repositories. However, if we need to use any secret keys in our circle tests, we need to add some extra steps. However, it looks like we don't.

It seems to be in Build Settings > Advanced Settings and the name of the option is "Build forked pull requests"

source: https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories

**Comment by shcheklein** [comment]
Enabled, please, try again!

**Comment by fabiosantoscode** [comment]
@shcheklein works fine :) had to fix some issues with the config, but have a look at #105. 

Sadly it doesn't seem to run in parallel with the netlify jobs, but that might've been a fluke.

**Comment by shcheklein** [comment]
@
