### ISSUE TITLE
generate types from graphQL schema

### ISSUE THREAD

**Issue by fabiosantoscode** [iterative/blog#106]
Hello!

There's a bunch of ways to generate typescript types from a graphQL schema. 

I've found these two:

 - https://github.com/tgriesser/apollo-codegen/blob/master/README.md
 - https://www.npmjs.com/package/graphql-schema-typescript

I was wondering if we should use one of these, as any change in the graphQL schema would start being type-checked against our code, making sure that if for example, we deprecate a certain field, it's not being used anywhere on the codebase.

If this seems like a good idea, I'll look a bit more into it, so this is more of a request for comments than an issue.

Cheers! :snowman:

**Comment by shcheklein** [comment]
@iAdramelk any opinion on this?

**Comment by fabiosantoscode** [comment]
It might even be possible to generate types from the queries themselves. That would make sure we didn't forget a field or two and are accidentally passing undefined around.

**Comment by iAdramelk** [comment]
@shcheklein @fabiosantoscode I have a little mixed feelings about it. On one hand having typed GraphQL is a plus and an important thing for the application stability.

On the other hand, automatically generated types from GraphQL schema is often quite messy, have hard to read names and not always easy to work with. We used `apollo-codegen` to autogenerate flow types for one of our projects year and a half ago, and I can't say that I was very happy with results.

So I'd say that it is an interesting thing to explore and to see if we can made an implementation that will be easy and convenient to use, but before I see the final results, I can't say how comfortable I will be with merging it to the project.

**Comment by fabiosantoscode** [comment]
I had a look at this and found that it would be very complicated to do that right now. There's a way to hook into tsc but you need to effectively create your own CLI and call their unstable API from within.

There's an issue about adding plugins to TSC. If that ever happens we can generate our types and they will be read by our editors' typescript plugins and the type checker.

https://github.com/microsoft/TypeScript/issues/16607

As per the type names, I think you're right. Names like IPageInfo (just an I plus the graphql type name) shouldn't be too bad though, and we already need to know the type name for writing fragments, but that doesn't stop us from using fields which are missing from a specific page query.

I think we can close this, and if that issue ever gets closed, we can look into it again and maybe write a simple plugin for generating types for Gatsby page and regular queries.
