### ISSUE TITLE
Italicized links with underscores breaks

### ISSUE THREAD

**Issue by andronovhopf** [iterative/blog#119]
I have a link in a section of text that is italicized, e.g.:

`_blab blah blah blah  [Cats](https://www.rottentomatoes.com/m/cats_2019)?_`

This gets rendered as everything italicized up to the first underscore. I tried switching to using *blah blah blah...* notation, but it looks like this gets switched back to underscore notation somehow when I commit? Not sure if that's part of our linter or whatnot. 

In any case, I can work around this with a link shortener for the affected link so it isn't critical. Just wanted to flag the issue.

**Comment by fabiosantoscode** [comment]
It's an upstream issue: https://github.com/remarkjs/remark/issues/470

We can work around it if we don't use pedantic mode. I'm not sure of what the impact of this would be, so I'd say let's see if a fix comes along or I/we can push one.
