### ISSUE TITLE
problems with displaying titles

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#12]
text is hidden behind title

<img width="320" alt="Screen Shot 2019-12-17 at 5 36 16 PM" src="https://user-images.githubusercontent.com/3659196/71048331-ed623700-20f3-11ea-975b-73fd909f158b.png">

long title is cut:

<img width="357" alt="Screen Shot 2019-12-17 at 5 36 22 PM" src="https://user-images.githubusercontent.com/3659196/71048349-f5ba7200-20f3-11ea-9c6c-904e382d9731.png">

**Comment by antiflasher** [comment]
Let's display Title as is but hide the Description with a gradient layer:
<img width="420" alt="Screenshot 2019-12-18 at 10 18 57" src="https://user-images.githubusercontent.com/5543839/71107744-c0d11c80-21d2-11ea-8059-fc3a005833a1.png">

**Comment by shcheklein** [comment]
@antiflasher what if title takes 3-4 lines? what is the limit here and how should we handle this.

I like the idea with gradient, btw. Not sure though it solves the problem.
