### ISSUE TITLE
meta: no card in discord

### ISSUE THREAD

**Issue by andronovhopf** [iterative/blog#121]
Looks like we need to specify image settings for discord

<img width="950" alt="Screen Shot 2020-02-18 at 12 58 05 PM" src="https://user-images.githubusercontent.com/29716724/74777420-4eba9980-524e-11ea-935c-7de278f4666c.png">

**Comment by shcheklein** [comment]
@fabiosantoscode could you take a look what's missing here?

**Comment by shcheklein** [comment]
Related #47

**Comment by fabiosantoscode** [comment]
I looked at the discord and the preview image is there.

This is probably a per-user setting, found in user settings > text & images > link preview which might be disabled.

**Comment by shcheklein** [comment]
It looks like for Discord it just takes time to process a new link. Not sure if we can optimize this process for it. I've seen this in other social networks. Again not sure if it's related to us or not (e.g. it might due to us doing redirects? social networks complain about this)

**Comment by fabiosantoscode** [comment]
I see. It could be the redirects, but only if they actively discriminate against URLs with redirects.

**Comment by shcheklein** [comment]
Yep, not 100% sure, but as you can see in the redirects ticket networks complain about this at least.

**Comment by shcheklein** [comment]
looks like also solved by #135
