### ISSUE TITLE
wasteful responsive image versions.

### ISSUE THREAD

**Issue by fabiosantoscode** [iterative/blog#123]
While investigating the image situation we have in our hands, I found a couple of inefficiencies when looking through the source code of [this post](https://blog.dvc.org/a-public-reddit-dataset). I went and verified that it works with JPG images as well.

 * We create a webp and png version for each image.

Support for webp is [very widespread](https://caniuse.com/#feat=webp), and if you're using IE11, you're not the common use case, so you can spend a few more milliseconds and download a large PNG.

 * We create too many versions of the images. 

These are the sizes we use: 175w, 350w, 700w, 1050w, 1400w, 1600w.

My problem is with the 175w and 350w sizes. There are no screens with this pixel width. Even the iPhone 4s was 640 pixels wide. Android phones also have high pixel density.

**Comment by shcheklein** [comment]
> My problem is with the 175w and 350w sizes. 

the should consume some negligible percent of the whole space

> Support for webp is very widespread, and if you're using IE11, you're not the common use case, so you can spend a few more milliseconds and download a large PNG.

sounds good if can easily optimize it this way

**Comment by fabiosantoscode** [comment]
I'm closing this since we're using S3, where space is not much of a premium.
