### ISSUE TITLE
on mobile reduce size of DVC code snippets

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#125]
Looks like we don't actually change the font size and they look huge.

**Comment by fabiosantoscode** [comment]
![Screenshot_20200221-183708923](https://user-images.githubusercontent.com/1611595/75061817-69ed0980-54d9-11ea-83f9-f4ddebbd60f1.jpg)

It looks fine on my phone (both Chrome and Firefox) Do they look larger than this on yours?

I had a look in the chrome devtools and the font size for DVC code is 14.8px, while text is 20px.

**Comment by shcheklein** [comment]
That's what I see on my iPhone:

![IMG_4F3BDF07FBBC-1](https://user-images.githubusercontent.com/3659196/75076581-72cbe400-54b5-11ea-912e-387f78f6b177.jpeg)

note the difference in size of the upper block and the bottom one.
