### ISSUE TITLE
changes in post's metadata break hot reload and dev mode

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#128]
try `content/blog/2019-08-01-july-19-dvc-heartbeat.md` file edits to the `pictureComment` can easily get rebuild into infinite cycle `running queries`.

no information why is it happening, no errors - super annoying and is breaking editors workflow. 

@iAdramelk  do you know if there is an easy way to avoid this in this future, easy way to run some tests for this? (this is not the first time it happens)?

**Comment by iAdramelk** [comment]
Never seen this bug before. Need to experiment to understand why it happened. Looks super weird.

**Comment by shcheklein** [comment]
@iAdramelk we had something similar before already, right? had to get to the previous version of Gatsby or some other libraries as far as I remember.

**Comment by iAdramelk** [comment]
@shcheklein we had a problem then images were recreated multiple times on each save. Not sure if this is the same thing or not.

**Comment by shcheklein** [comment]
it might be happening when there are some errors in the processing pipeline (for example Markdown has bugs).

**Comment by iAdramelk** [comment]
@shcheklein BTW, did this bug appears after we added MD support for the `pictureComment` or this is an old one?

**Comment by shcheklein** [comment]
@iAdramelk it's hard for me to answer this since I don't run it for a some long periods of time. It might be related to that change indeed.
