### ISSUE TITLE
images do not scale properly

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#13]
https://github.com/iterative/blog/pull/9/files#diff-fea3583130d538767cfdbfee3b122a7dR7

take a look at the rendered image in the PR, it's too lage

**Comment by shcheklein** [comment]
<img width="454" alt="Screen Shot 2019-12-17 at 9 44 24 PM" src="https://user-images.githubusercontent.com/3659196/71058969-6bcfd080-2116-11ea-9401-d8bf2e356a30.png">

**Comment by antiflasher** [comment]
I suggest to crop the Cover image with 4×3 ratio on CSS level. But the blog editor should pick images of horizontal orientation as all the design relies on it.
