### ISSUE TITLE
create markup/fix style for the horizontal text block splitter

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#14]
Medium:

<img width="757" alt="Screen Shot 2019-12-17 at 10 10 04 PM" src="https://user-images.githubusercontent.com/3659196/71060362-21e8e980-211a-11ea-8b55-49291c89bd3c.png">

us:

<img width="833" alt="Screen Shot 2019-12-17 at 10 11 18 PM" src="https://user-images.githubusercontent.com/3659196/71060388-2dd4ab80-211a-11ea-8e3b-88b16388dfa3.png">

**Comment by Rajjix** [comment]
Hey there, 
I think this should do the trick, must note that it's preferable to add a className to the hr elements you want to show as three dots and replace the hr tag with that className, so it doesn't break things on other pages.

hr::before {

    content: "...";
    position: absolute;
    left: 50%;
    font-size: 28px;
    font-style: italic;
    line-height: 1.4;
    letter-spacing: 0.6em;
    /* background: radial-gradient(circle at center, var(--color-light-gray) 50%,transparent 51%) 0 0px/10px 5px no-repeat, 
                radial-gradient(circle at center, var(--color-light-gray) 50%,transparent 51%) .6em 0px/10px 5px no-repeat,
                radial-gradient(circle at center, var(--color-light-gray) 50%,transparent 51%) 1.2em 0px/10px 5px no-repeat; */
    transform: translateX(-50%);
    margin-top: -30px;
  }
