### ISSUE TITLE
create forum links for posts we migrated

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#15]

**Comment by SvetaGr** [comment]
https://blog.dvc.org/blog/november-19-dvc-heartbeat/ - https://discuss.dvc.org/t/november-19-dvc-heartbeat/284

https://blog.dvc.org/blog/october-19-dvc-heartbeat/ - https://discuss.dvc.org/t/october-19-dvc-heartbeat/285

https://blog.dvc.org/blog/dvc-org-for-hacktoberfest-2019/ - https://discuss.dvc.org/t/dvc-org-for-hacktoberfest-2019/286

https://blog.dvc.org/blog/september-19-dvc-heartbeat/ - https://discuss.dvc.org/t/september-19-dvc-heartbeat/287

https://blog.dvc.org/blog/july-19-dvc-heartbeat/ - https://discuss.dvc.org/t/july-19-dvc-heartbeat/288

https://blog.dvc.org/blog/june-19-dvc-heartbeat/ - https://discuss.dvc.org/t/june-19-dvc-heartbeat/289

https://blog.dvc.org/blog/may-19-dvc-heartbeat/ - https://discuss.dvc.org/t/may-19-dvc-heartbeat/290

https://blog.dvc.org/blog/dvc-project-ideas-for-google-summer-of-docs-2019/ - https://discuss.dvc.org/t/dvc-project-ideas-for-google-season-of-docs-2019/291

https://blog.dvc.org/blog/april-19-dvc-heartbeat/ - https://discuss.dvc.org/t/april-19-dvc-heartbeat/292

https://blog.dvc.org/blog/march-19-dvc-heartbeat/ - https://discuss.dvc.org/t/march-19-dvc-heartbeat/293

https://blog.dvc.org/blog/ml-best-practices-in-pytorch-dev-conf-2018/ - https://discuss.dvc.org/t/ml-best-practices-in-pytorch-dev-conf-2018/294

https://blog.dvc.org/blog/best-practices-of-orchestrating-python-and-r-code-in-ml-projects/ - https://discuss.dvc.org/t/best-practices-of-orchestrating-python-and-r-code-in-ml-projects/295

https://blog.dvc.org/blog/ml-model-ensembling-with-fast-iterations/ - https://discuss.dvc.org/t/ml-model-ensembling-with-fast-iterations/296

https://blog.dvc.org/blog/data-version-control-in-analytics-devops-paradigm/ - https://discuss.dvc.org/t/data-version-control-in-analytics-devops-paradigm/297

https://blog.dvc.org/blog/r-code-and-reproducible-model-development-with-dvc/ - https://discuss.dvc.org/t/r-code-and-reproducible-model-development-with-dvc/298

https://blog.dvc.org/blog/dvc-0-8-5-release/ - https://discuss.dvc.org/t/dvc-0-8-5-release/299

https://blog.dvc.org/blog/how-a-data-scientist-can-improve-his-productivity/ - How A Data Scientist Can Improve His Productivity

**Comment by shcheklein** [comment]
@SvetaGr blog links are not valid anymore .. they go w/o `/blog/` part now. We should fix the forum posts. But before we do that we should review description, images, etc for the blog posts after we migrated them. 

E.g. https://blog.dvc.org/dvc-org-for-hacktoberfest-2019/ - has the Heartbeat's description. Also, all heartbeats have the same text - can we do something better?

**Comment by shcheklein** [comment]
Fixed by https://github.com/iterative/blog/commit/188eabae161b70bb5411d51e2fe1e00a56eeb801
