### ISSUE TITLE
yarn develop and localhost being odd

### ISSUE THREAD

**Issue by andronovhopf** [iterative/blog#151]
I'm doing the usual workflow for making a new blog post- clone, branch, and making changes to the blog contents locally. As usual, I've run `yarn` and `yarn develop` to run a local development server. Whenever I visit `http://localhost:8000/` in my browser, I'm being automatically re-directed to our current blog.dvc.org page- no sign of any of my new edits, or of being in a development server. 

It's possible something strange is going on with my browser causing this redirect, but wanted to check- has anything changed recently that could cause this?

**Comment by shcheklein** [comment]
@andronovhopf we migrated to blog to iterative/dvc.org - please, try that repo. This one is not active anymore. There is info here https://github.com/iterative/dvc.org#writing-blog-posts how to create a blog post in that main repo.
