### ISSUE TITLE
subscribe to the email list consider using captcha, add GA event

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#38]
We are getting bots subscribed to the list. Not clear where do they come from yet - but we need to add additional safeguards + add GA properly to see if subscriptions come from blog (and how many).

**Comment by fabiosantoscode** [comment]
I'm on this one

**Comment by fabiosantoscode** [comment]
After a user clicks the subscribe button, they're taken to mailchimp's site. I tried to see if they had an invisible captcha there, but it seemed like they didn't. So I looked into how to enable one and found these instructions:

https://mailchimp.com/help/about-recaptcha-for-signup-forms/#Enable_reCAPTCHA

Regarding google analytics, I'm getting on that one now.

**Comment by shcheklein** [comment]
can it be integrated with the way we embed the form? (we don't popup anything and design is custom)?

**Comment by fabiosantoscode** [comment]
> can it be integrated with the way we embed the form?

The captcha is on their site, when the user submits the form they're taken there and mailchimp can captcha them. So no integration on our own site. I hope. Their docs aren't terribly clear on this. If they don't captcha the user, we need to use our own API to validate their cache and subscribe them ourselves by doing a POST request, and disable clientside subscriptions.

**Comment by shcheklein** [comment]
@fabiosantoscode yeah, would like to avoid any heavy solutions or a separate page that asks for a captcha. If there are other ways to prevent bots abusing the form let's use them - like some JS library that obfuscates the form a bit? If there are nothing like this - let's just fix an even and return to this if we have one more spike of subscriptions.

**Comment by fabiosantoscode** [comment]
@shcheklein they already have a page, the captcha would be on there, so no more pages. Even if it was on our end, we could do it with zero new pages, given we can use an invisible captcha on the subscribe button.

Go ahead and subscribe yourself, with a throwaway e-mail like grr.la (only pokemail.net domain works) https://www.guerrillamail.com/. You get taken to a page on a mailchimp domain to confirm your subscription. That's where the captcha would be located.

**Comment by shcheklein** [comment]
> we could do it with zero new pages, given we can use an invisible captcha on the subscribe button.

what are the benefits of using an invisible captcha?

> You get taken to a page 

yep, that's what I would like to avoid for now. Let's keep it simple and see if we get another spike of subscriptions.

**Comment by fabiosantoscode** [comment]
> what are the benefits of using an invisible captcha?

You don't have to click an "I am not a robot" checkbox. If recaptcha suspects you're a robot, you'll see the usual popup. The only visible element it has, is either their logo floating on the bottom-right of the page (not a good option I think) or the following text which we need to add ourselves before the submit button:

>     This site is protected by reCAPTCHA and the Google
>     Privacy Policy and
>    Terms of Service apply.

> yep, that's what I would like to avoid for now.

We would need extra work for users not to be taken to the mailchimp page. I'll add an issue when we have serverless functions to do it with.

**Comment by shcheklein** [comment]
> We would need extra work for users not to be taken to the mailchimp page. I'll add an issue when we have serverless functions to do it with.

yep, let's not deal with it for now
