### ISSUE TITLE
support basic markup in meta fields

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#39]
For example, we need to put links into `pictureComment` or support newlines/paragraph splits in `descriptionLong`.

**Comment by shcheklein** [comment]
Example of links in the title image: https://blog.dataversioncontrol.com/june-19-dvc-%EF%B8%8Fheartbeat-505900be9aac

**Comment by shcheklein** [comment]
Example of newlines in the "description long" - https://blog.dataversioncontrol.com/june-19-dvc-%EF%B8%8Fheartbeat-505900be9aac

**Comment by iAdramelk** [comment]
@shcheklein It's technically possible, but we will have additional problems then. For example `descriptionLong` is used for the meta tags and you can't have tags there. And if we remove tags from there automatically it can came out awkward: Texts instead of links, multiple paragraphs that became one paragraph, etc. What is the best way to approach that?

**Comment by sekmet** [comment]
@shcheklein I got fixed #25 and #39

**Comment by shcheklein** [comment]
@iAdramelk can we strip markup when we need to put those into meta fields?

**Comment by iAdramelk** [comment]
@shcheklein we can, but text can loose meaning if we replace link with text or concat paragraphs.

**Comment by shcheklein** [comment]
@iAdramelk I think links to text and concatenation should work fine? why do you have concerns about this? any specific examples in your mind?

**Comment by iAdramelk** [comment]
@shcheklein the are no technical problems, only content one.

For example if we write something like that in description:

> Please check [this link].
>
> Some new paragraph.

And then replace it with:

> Please check this link. Some new paragraph.

And then place it in say feed or in the Facebook snippet it can look strange and meaningless.

**Comment by shcheklein** [comment]
yep, agreed. But still does not look like a deal breaker to me. Newlines are fine. Link - hard to predict but should be more or less fine either (I doubt that we will have [this link] type of phrase in that block - it's too important). Links in image subtitles - probably fine as well.

**Comment by fadilmamedov** [comment]
@shcheklein please, assign this to me. Thanks!
