### ISSUE TITLE
if inline code block is a link highlight it somehow

### ISSUE THREAD

**Issue by shcheklein** [iterative/blog#41]
E.g. underline with black?

**Comment by shcheklein** [comment]
@frontexpert is it fixed also?

**Comment by frontexpert** [comment]
Do you mean this case? (in the case that link include inline code block)
![Screenshot at Jan 28 02-57-03](https://user-images.githubusercontent.com/19707900/73226833-1b6a7a80-417a-11ea-9e74-51b4c36c50b9.png)

**Comment by frontexpert** [comment]
If this is the case, I already applied link color - blue. just like above screenshot.
And if the link is active, all the link text(including code text) will change to Orange color.

**Comment by shcheklein** [comment]
thanks, resolving this then! Fixed by #81

**Comment by frontexpert** [comment]
Sounds good. I didn't know this issue-41 before. i thought this is included in the issue-44
Thanks.

**Comment by shcheklein** [comment]
@frontexpert yep, the about styles =was more general and included this one.
