### ISSUE TITLE
option for text wrapping

### ISSUE THREAD

**Issue by andronovhopf** [iterative/blog#71]
It would be great to have an option to wrap text, as is that doesn't seem to be doable by manipulating the html <img> parameters. 

![image](https://user-images.githubusercontent.com/29716724/72655123-d196be80-3947-11ea-92cd-fec1b38201be.png)

**Comment by fabiosantoscode** [comment]
Is this issue about floating the image to the left or right and allowing the text on either side to flow around the image?

Maybe we should pair this with a way for writers to add a clearfix, denoting when it's time for the text to stop flowing by.

![Screenshot from 2020-02-04 15-37-17](https://user-images.githubusercontent.com/1611595/73759705-3d5c9200-4764-11ea-9046-e2d58415989b.png)

The clearfix marker might be expressed in markdown as a fake HTML element (`<clearfix />`) which gets turned into a div with the appropriate class, or left alone as a CSS-only "custom element". As long as it has `display: block` it renders fine.

**Comment by shcheklein** [comment]
> Is this issue about floating the image to the left or right and allowing the text on either side to flow around the image?

yes!

Not sure about the solution. May be we can piggy back on the image title like @frontexpert did with image sizes?

**Comment by fabiosantoscode** [comment]
@shcheklein works for me! I'll wait for his PR to be merged and hop onto this.
