### ISSUE TITLE
embedding Twitter links

### ISSUE THREAD

**Issue by andronovhopf** [iterative/blog#74]
Would be great to have an easier tweet embedding, like `{% twitter 834439977220112384 %}` in https://dev.to/p/editor_guide

**Comment by frontexpert** [comment]
Hi, @shcheklein  How are you? I hope you are going well. btw, I just saw you post a new job - https://www.upwork.com/jobs/~01040ff058e8af8107

So is it impossible for me to work on the Github Issues again? I already sent my proposal for your new job. Especially, I applied a further lower rate of $33/hr than before for your long term relationship. I was working on the Gatsby project until now so my skills were enhanced a bit more, I think.

In particular, I found many issues I can fix easily on the github issues list - https://github.com/iterative/dvc.org/issues
I will look forward to hearing from you soon.

Thanks. :)
